Add a config option to specify custom command-line option
34736384/genshin-fps-unlock pull request #477
Opened 2024-10-18 07:40 UTC by littlewu2508

Closes: https://github.com/34736384/genshin-fps-unlock/issues/476

2024-10-18 08:06 UTC, littlewu2508 commented
I have compiled it on Debian with the modification of https://github.com/34736384/genshin-fps-unlock/pull/478: 
[unlockfps_nc_custom_option.zip](https://github.com/user-attachments/files/17430678/unlockfps_nc.zip)

2024-10-23 06:26 UTC, 34736384 requested changes
Hello, please see the requested changes below

2024-10-23 06:26 UTC, 34736384 commented on unlockfps_nc/Model/Config.cs
> +        public string CustomOption { get; set; } = "";
```suggestion
        public string AdditionalCommandLine { get; set; } = "";
```
'CustomOption' seems to be ambiguous about what it does

2024-10-23 06:26 UTC, 34736384 commented on unlockfps_nc/Service/ProcessService.cs
> +            commandLine += $"{_config.CustomOption} ";
```suggestion
            commandLine += $"{_config.AdditionalCommandLine} ";
```

2024-10-23 06:41 UTC, merged